import React, { Component } from 'react';
import Project from "../Portfolio/components/Project";
import WeatherPic from "../../assets/weather.jpg";
import drinks from "../../assets/tulips-drink-and-books.jpg";
import burger from "../../assets/burger.jpg";
import note from "../../assets/note.jpg";
import directory from "../../assets/employeedir.PNG";
import fitness from "../../assets/dashboard.PNG";
import jobspot from "../../assets/jobSpotScreenShot.png"
import eInfo from "../../assets/employeeInfo.PNG"
import "./style.css";

const portfolioInfo = [
    {
        id: 1,
        title: "React Employee Directory",
        picture: directory,
        repo: "https://github.com/Knzmck/employee-directory.git",
        app: "https://employee-directory-of-wonder.herokuapp.com/",
        description: "A react application where users can sort and search through a directory of employees generated by an API."
    },
    {
        id: 2,
        title: "JobSpot",
        picture: jobspot,
        repo: "https://github.com/Anverch/JobSpot.git",
        app: "https://job-spot.herokuapp.com/",
        description: "A full stack application (MySQL, Express, React & Node) where users can store and organize information while exploring job opportunities."
    },
    {
        id: 3,
        title: "Drinking@Home- Cocktail Finder",
        picture: drinks,
        repo: "https://github.com/Knzmck/Drinking-At-Home.git",
        app: "https://knzmck.github.io/Drinking-At-Home/",
        description: "A front end application which uses an API to generate cocktail recipes based on keyword searches and relevant categories."
    },
    {
        id: 4,
        title: "Classic Note-Taker",
        picture: note,
        repo: "https://github.com/Knzmck/note-taker.git",
        app: "https://radiant-dusk-28475.herokuapp.com/",
        description: "A front end application for taking notes and keeping your thoughts organized."
    },
    {
        id: 6,
        title: "Fitness Tracker",
        picture: fitness,
        repo: "https://github.com/Knzmck/fitness-app.git",
        app: "https://workin-out.herokuapp.com/",
        description: "A full stack application (Mongo, Express, React & Node) where users can keep track of their workouts and fitness routines."
    },
    {
        id: 7,
        title: "Eat-da-Burger",
        picture: burger,
        repo: "https://github.com/Knzmck/burger.git",
        app: "https://eat-da-burger-nomnom.herokuapp.com/",
        description: "A full stack application (MySQL, Express, Handlebars, Node & homemade ORM) where users can create & devour 'burgers'."
    },
    {
        id: 8,
        title: "Weather Forecaster",
        picture: WeatherPic,
        repo: "https://github.com/Knzmck/weather-dashboard.git",
        app: "https://knzmck.github.io/weather-dashboard/",
        description: "Front end application using an APIs to render weather forecasts for any city in the world."
    },
    {
        id: 9,
        title: "Employee Information Generator",
        picture: eInfo,
        repo: "https://github.com/Knzmck/employee-summary.git",
        app: "#",
        description: "Node & express application (no demo available) where employers can type in information about their employees to generate an HTML page with relevant information."
    }
]

class Portfolio extends Component {

    render() {
        return (
            <main className="portfolio-container">
                <div className="row">
                    <h2 className="portfolio-header mt-4"> Portfolio </h2>
                </div>
                <div className="row">
                    <Project projects={portfolioInfo} />
                </div>
            </main>
        );
    }
}

export default Portfolio;